version: '3.8'

services:
  consumer-flask1:
    image: consumer-flask
    container_name: consumer-flask1
    env_file:
      - .env
    restart: always

  consumer-flask2:
    image: consumer-flask
    container_name: consumer-flask2
    env_file:
      - .env
    restart: always

  consumer-flask3:
    image: consumer-flask
    container_name: consumer-flask3
    env_file:
      - .env
    restart: always

  haproxy:
    image: haproxy
    container_name: haproxy
    volumes:
      - ./haproxy/conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 8080:80
    depends_on:
      - flask1
      - flask2
      - flask3
      - flask4

  flask1:
    image: my_flask
    container_name: flask1
    env_file:
      - .env
    volumes:
      - ./flask/src:/opt/src

  flask2:
    image: my_flask
    container_name: flask2
    env_file:
      - .env
    volumes:
      - ./flask/src:/opt/src

  flask3:
    image: my_flask
    container_name: flask3
    env_file:
      - .env
    volumes:
      - ./flask/src:/opt/src

  flask4:
    image: my_flask
    container_name: flask4
    env_file:
      - .env
    volumes:
      - ./flask/src:/opt/src
